# PowerShell® is subject to trademark!

name: PowerShell virtual environment

# Controls when the action will run. Workflow runs when manually triggered using the UI

# or API.

on:

  workflow_dispatch:

    # Inputs the workflow accepts.

    inputs:

      command:

        # Friendly description to be shown in the UI instead of 'name'

        description: 'Command to run (defaults to HW command)'

        # Default value if no value is explicitly provided

        default: 'echo "Hello World"'

        # Input has to be provided for the workflow to run

        required: false

        

      vm:

        description: Windows version (2019 or latest)

        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "windows"

  windows:

    # The type of runner that the job will run on

    runs-on: windows-${{ github.event.inputs.vm}}

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

    # Runs a single command using the runners shell

    - name: Run command

      run: ${{ github.event.inputs.command }}
